---
title: "2020 USGS Wisconsin Data"
output: html_notebook
output: html_notebook
project: "USGS affinis habitat and floral use"
author: Jade Kochanski
lead_investigators: Ian Pearse and John Mola
---
# READ ME: about this data and code
```{r}
# All .csv files should have already been downloaded for entry into the Google Form. There are separate .csv files for the background points and observations at each unique site/date survey.
#I moved all background points .csv files into a folder within my R working directory. I also moved all of the observation .csv files into a folder in my R working directory.
```

---
# Load packages
```{r}
library(tidyverse) #for general data handling/commands
library(ggplot2) #visualizations
library(fs) #for batch uploading csv files
library(lubridate) #working with dates
```

# Load and tidy data
## background points
```{r}
# To upload many .csv files as a batch:
## adapted from the instructions here:
data_dir <- "./background_points" 

fs::dir_ls(data_dir)

#load all csv files from the folder
csv_files <- fs::dir_ls(data_dir, regexp = "\\.csv$")
csv_files

readr::read_csv(csv_files[1])

#create a data frame that is the combination of all csv files
background.pts <- csv_files %>% 
  map_dfr(read_csv, .id = "source") #this line creates a column so you know which csv file the observation originated from.

background.pts #take a look at the df

#the source column creates this really long identifier 
##(e.g., “./observations/CapSprings_21May2020_Walk1 - observations.csv”)
#Clean this up so site, date, walk number are in separate columns. 

background.pts <- background.pts %>%
  separate(source, sep = "/", into = c(NA, NA, "visit")) %>%
  separate(visit, sep = "-", into = c("visit", NA)) %>%
  separate(visit, sep = "_", into = c("site", "date", "walk_number"))

background.pts <- background.pts %>%
  mutate(date = dmy(date))

background.pts <- background.pts %>%
  mutate(week = week(date))

#To call specific columns while visualizing the data, column names that began with a number needed to be renamed.
##For example: “10m_landcover” was changed to “landcover_10m”
background.pts <- background.pts %>%
  rename(landcover_10m = "10m_landcover",
         microsite_2m = "2m_microsite",
         microsite_extra_2m = "2m_microsite_extra",
         flower_species1_2m = "2m_flower_species1",
         flower_cover1_2m ="2m_flower_cover1",
         flower_species2_2m = "2m_flower_species2",
         flower_cover2_2m = "2m_flower_cover2")

```

## observations
```{r}
# repeat the process from the above chunk to upload all of the observation csv files
data_dir_obs <- "./observations"

fs::dir_ls(data_dir_obs)

csv_files_obs <- fs::dir_ls(data_dir_obs, regexp = "\\.csv$")
csv_files_obs

readr::read_csv(csv_files_obs[1])

#combine files into one df
observations <- csv_files_obs %>% 
  map_dfr(read_csv, .id = "source")

observations

## tidy columns
observations <- observations %>%
  separate(source, sep = "/", into = c(NA, NA, "visit")) %>%
  separate(visit, sep = "-", into = c("visit", NA)) %>%
  separate(visit, sep = "_", into = c("site", "date", "walk_number")) 

observations <- observations %>%
  mutate(date = dmy(date))

observations <- observations %>%
  mutate(week = week(date))

observations <- observations %>%
  rename(microsite_2m = "2m_microsite",
         microsite_extra_2m = "2m_microsite_extra")

observations <- observations %>%
  filter(microsite_2m != "NA") #remove the 4 NAs so they do not clutter the graph later
```

# Visuals
## background points
### 10-m landcover
```{r}
#visual summaries of 10-m landcovers for all background points.

ggplot(background.pts, aes(x = week, fill = landcover_10m)) + geom_bar(stat = "count") +
  theme_bw() +  
  scale_fill_manual(values = c("#636363", "#cbc9e2", "#2ca25f", "#43a2ca","#006d2c"))

```

### edge types
```{r}
#a separate visual summary of the edge types for 10-m landcover

#create a new dataframe that only keeps data from background points that were recorded as edge.
bkgrdpts <- background.pts %>%
  filter(edge_types != "NA")
  
ggplot(bkgrdpts, aes(x = week, fill = edge_types)) + geom_bar(position = "stack", width = 0.75) + 
  theme_bw()
```

### microsites
```{r}
#visual summary of the microsite types recorded at each background point. 
##the three most common seem to be herbaceous litter, grass (turf + tussock), and leaf litter

ggplot(background.pts, aes(x = week, fill = microsite_2m)) + geom_bar(position = "stack", width = 0.75) + 
  theme_bw() +  
  scale_fill_manual(values = c("#8c510a", "#d8b365", "#1b7837", "#999999", "#91cf60", "#1a9850", "#ec7014")) #i made the colors so they made sense to me (e.g., brown for bareground or soil) but they can be changed to anything
```

## observations 
### microsites
```{r}
ggplot(observations, aes(x = week, fill = microsite_2m)) + geom_bar(position = "stack", width = 0.75) + 
  theme_bw() +  
  scale_fill_manual(values = c("#8c510a", "#c994c7", "#d8b365", "#1b7837", "#7fbf7b", "#999999", "#91cf60", "#1a9850", "#ec7014"))

```


